name: Development

on:
  push:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main
      - staging
      - development

jobs:
  format:
    name: Format codebase
    runs-on: ububtu-latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "install npm@latest"
        uses: npm i -g npm@latest

      - name: "install dependencies"
        uses: bahmutov/npm-install@v1

      - name: "run prettier formatter"
        uses: npm run format

  lint:
    name: Check code syntax
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "install npm@latest"
        uses: npm i -g npm@latest

      - name: "install dependencies"
        uses: bahmutov/npm-install@v1

      - name: "run eslint syntax checks"
        uses: npm run lint
